# Generated by Django 2.2.1 on 2019-05-21 22:01

import datetime
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePromo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('matieres', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', django.contrib.postgres.fields.jsonb.JSONField()),
                ('image', models.FileField(upload_to='profile/')),
                ('codePromo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='utask.CodePromo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('startDate', models.DateTimeField(default=datetime.datetime(2019, 5, 21, 22, 1, 53, 390351))),
                ('endDate', models.DateTimeField()),
                ('status', models.CharField(choices=[('Important', 'Important'), ('Finis', 'Finis'), ('En cours', 'En cours'), ('A faire', 'A faire')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='taskFiles/')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskTags', to='utask.Color')),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takLists', to='utask.Task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='files',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='utask.TaskFile'),
        ),
        migrations.AddField(
            model_name='task',
            name='madeBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='utask.Profile'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='utask.TaskTag'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('startDate', models.DateField(default=datetime.date(2019, 5, 21))),
                ('endDate', models.DateField()),
                ('image', models.FileField(upload_to='projectImages/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='utask.Profile')),
                ('members', models.ManyToManyField(to='utask.Profile')),
                ('taskList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='utask.TaskList')),
            ],
        ),
    ]
