# Generated by Django 2.2.1 on 2019-05-26 17:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utask', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='taskList',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='taskList',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='utask.TaskList'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasklist',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='takLists', to='utask.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(default=datetime.date(2019, 5, 26)),
        ),
        migrations.AlterField(
            model_name='task',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 17, 36, 6, 963050)),
        ),
    ]
