# Generated by Django 2.2.1 on 2019-05-26 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utask', '0002_auto_20190526_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(null=True, upload_to='projectImages/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(default=datetime.date(2019, 5, 26), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 26, 19, 42, 47, 887203)),
        ),
    ]
