# Generated by Django 2.2.1 on 2019-05-28 15:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utask', '0003_auto_20190526_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(default=datetime.date(2019, 5, 28), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='files',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='utask.TaskFile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='startDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 15, 43, 58, 808241)),
        ),
    ]
